wandb_version: 1

AE_iter:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.9.5
    start_time: 1632078443
    t:
      1:
      - 1
      - 5
      4: 3.9.5
      5: 0.12.1
      8:
      - 1
      - 2
      - 5
add_z_min:
  desc: null
  value: 0.0001
ae_end_conj:
  desc: null
  value: false
ae_end_diffloss:
  desc: null
  value: 0.01
base_model:
  desc: null
  value: wgan
batch_size:
  desc: null
  value: 2048
beta1:
  desc: null
  value: 0.5
clip_value:
  desc: null
  value: 0.01
dataset:
  desc: null
  value: cifar10
device:
  desc: null
  value: cuda:1
dis_layer:
  desc: null
  value: 8
dis_step:
  desc: null
  value: true
epochs:
  desc: null
  value: 100
force_gen_real_info:
  desc: null
  value: false
img_size:
  desc: null
  value: 32
latent_dim:
  desc: null
  value: 10
latent_layer:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.0001
n_critic:
  desc: null
  value: 5
n_iter:
  desc: null
  value: 3
ndf:
  desc: null
  value: 64
ngf:
  desc: null
  value: 64
nz:
  desc: null
  value: 100
project_name:
  desc: null
  value: SMEG GAN
run_test:
  desc: null
  value: false
sample_img_num:
  desc: null
  value: 16
save_image_interval:
  desc: null
  value: 5
smeg_gan:
  desc: null
  value: true
wandb:
  desc: null
  value: true
